### ISSUE TITLE
request to support things like

### ISSUE THREAD

**Issue by berlinguyinca** [jirutka/rsql-parser#12]
dear Sir,

we were wondering, what the correct way would be to execute the following query

example:

metaData==(name=='license' and value=='CC BY-SA')

our object looks like this and is stored in Mongo and Elastic Search

http://mona.fiehnlab.ucdavis.edu/rest/spectra/252

and we want to query:

give me all data,. which have the metaData name=license and the metaData value='CC BY-SA'

kind regards,

Gert

p.s. really like the general concept and would love to utilize it in our system

**Comment by berlinguyinca** [comment]
the related mongo query would be:

db.getCollection('SPECTRUM').find({ "metaData" :  {$elemMatch : { "name":"license", "value" : "CC BY-SA"}} })

**Comment by jirutka** [comment]
Sorry for long delay, I’ve somehow missed this issue.

The solution is simple, just use double quotes for that argument:

```diff
- metaData==(name=='license' and value=='CC BY-SA')
+ metaData=="(name=='license' and value=='CC BY-SA')"
```
