### ISSUE TITLE
How to use limit and offset

### ISSUE THREAD

**Issue by t2349** [jirutka/rsql-parser#14]
Hi, All,

Thanks for all your contribution to the project, I am using this library for my project, I like it very much, but I have a problem about how to set the limit and offset of all the records I retrieve, I checked the testLimit() in the JUnit testing code, but when I use this url:
/rsql?search=userName==*S*;limit(0,10);
I got exception:
Request processing failed; nested exception is cz.jirutka.rsql.parser.RSQLParserException: cz.jirutka.rsql.parser.ParseException: Encountered " "(" "( "" at line 1, column 20.

So what is the url format to use limit for pagination?

Thanks
Dave

**Comment by jirutka** [comment]
Please see #9. Just use plain URI parameters offset and limit, don’t mix pagination with filtering/searching.
