### ISSUE TITLE
ability to pass nulls in rsql grammer

### ISSUE THREAD

**Issue by gauravbrills** [jirutka/rsql-parser#16]
Is there a syntax to pass nulls in rsql grammer 

I try to pass something like say `name==tom;ssn==`  to find names with no ssn but seems the parser gives an exception when there is no parameter post the == .This I am using to pass null values int eh expression .

Is there any way to do this or will it need to be added as an exception in the parser to handle null queries .

**Comment by jirutka** [comment]
You can use `ssn==null` and handle it in a converter. RSQL parser is not responsible for interpreting comparison arguments, it just pass them as a string value to a converter.

**Comment by gauravbrills** [comment]
@jirutka  thanks for the clarification . Think then we will have to define a custom logic or nomenclature for nulls in our API .

**Comment by jirutka** [comment]
Yeah, you surely already have some logic to convert numeric arguments into Integers, dates into some Date type... this is basically the same, it's just a type conversion.
