### ISSUE TITLE
Semicolon as “AND”?

### ISSUE THREAD

**Issue by tYYGH** [jirutka/rsql-parser#18]
With [the semicolon already a param-separator in the HTML spec](http://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2), isn’t it a problem that RSQL wants to use the semicolon as its own operator?

**Comment by vineey** [comment]
it should have no issue, html url encoding should handle this one.

**Comment by jirutka** [comment]
It’s quite complicated with the reserved chars in URI, but if nothing changed since I’ve done the research, it should be okay inside query string, i.e. no encoding is necessary.

**Comment by vineey** [comment]
@jirutka either way, they just have to use a library to handle the conversion from String to url params. In this way, developer doesn't need to be bother by the details.
