### ISSUE TITLE
Spliting in modules

### ISSUE THREAD

**Issue by diorcety** [jirutka/rsql-parser#3]
Hi,

At first thanks for your work.
I started to work on hibernate visitor on cxf fiql project, but this project is too messy.
I forked your work for support that hibernate and RSQL Builder using cxf ones.
For that i need to support RSQL parser from RSQL AST and definition

here the result https://github.com/diorcety/rsql

Regards,

**Comment by vineey** [comment]
@diorcety Your goal is already supported by rsql-parser architecture. It already expose an API, RSQLVisitor, wherein you can implement this interface to integrate with any kind of builder you need to make it work with your desired backend framework.
