### ISSUE TITLE
Java 1.6 Compatability

### ISSUE THREAD

**Issue by Lobanz** [jirutka/rsql-parser#5]
RSQL-Parser is currently not compatible with Java 1.6 but it easily could be.  It just uses <> and "|" exception matching which are 1.7 source level constructs.  Other than those two things, it's fine for 1.6.  I have found this project useful but I'm constrained to 1.6 by customer environment.  Would be nice to make these small changes and have it work for 1.6.

**Comment by jirutka** [comment]
I’ve merged (and fixed) your PR in branch `jdk6` and released version 2.0.0-jdk6 (it’ll be in Maven Central in few hours). However, I do not plan to backport future updates to it.

JDK6 is 9 years old and 2 years ago has reached end of life. I don’t want to support such ancient version just for some reactionary companies.

**Comment by Lobanz** [comment]
Wow.  Thanks.  I know what you mean about jdk6.  Im dealing with government
systems that are VERY slow to upgrade.  I grabbed the source and fixed it
myself but having it at maven central will get it out of my source tree.
Thanks!
